### ISSUE TITLE
Use Integrated jetty / tomcat

### ISSUE THREAD

**Issue by rohitvvv** [jughyd/MVCBookStore#13]
Make use of integrated jetty to run the project.

**Comment by shrinubabu** [comment]
Added Apache tomcat build plugin to run the project as tomcat is more popular than Jetty. Please comment if you have some other opinion.

**Comment by jbuddha** [comment]
tomcat should be sufficient. any one way to run the application without having to download additional software should be good

**Comment by jbuddha** [comment]
I merged the pull request.

**Comment by rohitvvv** [comment]
This is fixed. Verified.
